### ISSUE TITLE
js da o'zgartirilishi mumkin bo'lgan kodlar

### ISSUE THREAD

**Issue by ozbeg** [UmarAbdurazzoq/currency-converter#2]
<img width="613" alt="Screen Shot 2020-11-10 at 11 09 14" src="https://user-images.githubusercontent.com/68459737/98634446-2d05c300-2345-11eb-8950-372c151113cd.png">
o'zgaruvchilarga formni qo'shib uning ichidan qolgan elementlarni tanlab olgan Yaxshi

**Comment by UmarAbdurazzoq** [comment]
fixed this issue
