### ISSUE TITLE
formatting submit holatini eshitish kerak :))

### ISSUE THREAD

**Issue by ozbeg** [UmarAbdurazzoq/currency-converter#3]
<img width="613" alt="Screen Shot 2020-11-10 at 11 11 46" src="https://user-images.githubusercontent.com/68459737/98634673-8968e280-2345-11eb-869a-3caccfd2a301.png">
buttoning submit holatini eshitish kerak menimcha lekin formaning submit holati eshitilsa nur ustiga a'lo nur

**Comment by UmarAbdurazzoq** [comment]
fixed this issue
